[profile.default]
optimizer_runs = 30
solc_version = '0.8.33'
evm_version = 'cancun'
bytecode_hash = "none"
cbor_metadata = false
ignored_warnings_from = ["lib/"]

[profile.ci]
optimizer_runs = 30
solc_version = '0.8.33'
evm_version = 'cancun'
bytecode_hash = "none"
cbor_metadata = false
ignored_warnings_from = ["lib/"]
fuzz = { runs = 10000 }

[rpc_endpoints]
# mainnet
mainnet = "${RPC_URL_MAINNET}"
arbitrum = "${RPC_URL_ARBITRUM}"
base = "${RPC_URL_BASE}"
bsc = "${RPC_URL_BSC}"
scroll = "${RPC_URL_SCROLL}"

# testnet
sepolia = "${RPC_URL_SEPOLIA}"
arbitrum-sepolia = "${RPC_URL_ARBITRUM_SEPOLIA}"
base-sepolia = "${RPC_URL_BASE_SEPOLIA}"
bsc-testnet = "${RPC_URL_BSC_TESTNET}"
scroll-sepolia = "${RPC_URL_SCROLL_SEPOLIA}"

[etherscan]
# mainnet
mainnet = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
bsc = { key = "${BSCSCAN_KEY}", url = "https://api.bscscan.com/api" }
scroll = { key = "${SCROLLSCAN_API_KEY}", url = "https://api.scrollscan.com/api" }

# testnet
sepolia = { key = "${ETHERSCAN_KEY}" }
arbitrum-sepolia = { key = "${ARBISCAN_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
base-sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
bsc-testnet = { key = "${BSCSCAN_KEY}", url = "https://api-testnet.bscscan.com/api" }
scroll-sepolia = { key = "${SCROLLSCAN_API_KEY}", url = "https://api-sepolia.scrollscan.com/api" }
